# Learn About Apartment Data

https://mlbook.explained.ai/intro.html

In [40]:
import pandas as pd
df = pd.read_csv("../data/rent-ideal.csv")

In [41]:
df.head()

   bedrooms  bathrooms  latitude  longitude  price
0         1        1.0   40.7108   -73.9539   2400
1         2        1.0   40.7513   -73.9722   3800
2         2        1.0   40.7575   -73.9625   3495
3         3        1.5   40.7145   -73.9425   3000
4         0        1.0   40.7439   -73.9743   2795

In [42]:
df.head().T

                   0          1          2          3          4
bedrooms      1.0000     2.0000     2.0000     3.0000     0.0000
bathrooms     1.0000     1.0000     1.0000     1.5000     1.0000
latitude     40.7108    40.7513    40.7575    40.7145    40.7439
longitude   -73.9539   -73.9722   -73.9625   -73.9425   -73.9743
price      2400.0000  3800.0000  3495.0000  3000.0000  2795.0000

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48300 entries, 0 to 48299
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   bedrooms   48300 non-null  int64
 1   bathrooms  48300 non-null  float64
 2   latitude   48300 non-null  float64
 3   longitude  48300 non-null  float64
 4   price      48300 non-null  int64
dtypes: float64(3), int64(2)
memory usage: 1.8 MB

In [44]:
df.columns

Index(['bedrooms', 'bathrooms', 'latitude', 'longitude', 'price'], dtype='object')

In [45]:
df.describe()

           bedrooms     bathrooms      latitude     longitude         price
count  48300.000000  48300.000000  48300.000000  48300.000000  48300.000000
mean       1.508799      1.178313     40.750782    -73.972365   3438.297950
std        1.092232      0.426120      0.039560      0.029563   1401.422247
min        0.000000      0.000000     40.571200    -74.094000   1025.000000
25%        1.000000      1.000000     40.728100    -73.991700   2495.000000
50%        1.000000      1.000000     40.751600    -73.977900   3100.000000
75%        2.000000      1.000000     40.774000    -73.954700   4000.000000
max        8.000000     10.000000     40.915400    -73.700100   9999.000000

In [46]:
df.mean()

bedrooms        1.508799
bathrooms       1.178313
latitude       40.750782
longitude     -73.972365
price        3438.297950
dtype: float64

In [47]:
df.bedrooms.value_counts()

bedrooms
1    15718
2    14451
0     9436
3     6777
4     1710
5      169
6       36
8        2
7        1
Name: count, dtype: int64

In [48]:
df.sort_values('price', ascending=False).head()

       bedrooms  bathrooms  latitude  longitude  price
20589         3        3.0   40.7934   -73.9743   9999
3784          6        3.0   40.7287   -73.9856   9999
11598         6        3.0   40.7287   -73.9856   9999
43789         3        3.0   40.7602   -73.9597   9995
43085         2        2.5   40.7285   -73.9902   9995

In [50]:
df.price.head()

0    2400
1    3800
2    3495
3    3000
4    2795
Name: price, dtype: int64

In [51]:
prices = df.price
prices.min(), prices.mean(), prices.max()

(1025, 3438.297950310559, 9999)

In [53]:
df[['bedrooms', 'price']].head()

   bedrooms  price
0         1   2400
1         2   3800
2         2   3495
3         3   3000
4         0   2795

In [19]:
result = [[157.0, 242.0, 327.0, 412.0, 497.0, 582.0, 667.0, 752.0, 837.0, 922.0, 1007.0, 1092.0, 1177.0, 1262.0, 1347.0], 
          [314.0, 11466.0, 21668.0, 23272.0, 40847.0, 44511.0, 64534.0, 64696.0, 69224.0, 69103.0, 69245.0, 79975.0, 90034.0, 103567.0, 103661.0], 
          [
              [27.277495301504974, 1.7137960582690681, 1.0084033613445378, 0.6722689075630254, 0.3361344537815127], 
              [44.8943020731654, 1.8939393939393923, 1.2974976830398517, 1.2974976830398517, 0.9267840593141798], 
              [33.19249989073268, 1.2908777969018903, 1.0126582278481016, 0.6751054852320675, 0.33755274261603374], 
              [36.89447690088725, 1.620370370370372, 1.3528748590755355, 1.1273957158962795, 0.6764374295377678], 
              [42.647765847404536, 1.7402945113788482, 2.3376623376623376, 2.3376623376623376, 1.2987012987012987], 
              [38.41256428561022, 1.498637602179842, 1.8494055482166447, 1.5852047556142663, 1.0568031704095113], 
              [27.83257331837585, 1.3803680981595123, 1.1851851851851851, 0.8888888888888888, 0.5925925925925926], 
              [30.383601159690556, 0.770925110132159, 1.0741138560687435, 0.8592910848549948, 0.644468313641246], 
              [20.816154081498855, 1.3333333333333308, 1.6913319238900635, 1.6913319238900635, 0.0], 
              [35.322484301927474, 9.734513274336287, 13.23529411764706, 11.76470588235294, 7.352941176470589], 
              [36.53462317341453, 4.8128342245989275, 8.57142857142857, 7.619047619047619, 6.666666666666667], 
              [35.95769169131252, 3.74149659863946, 5.678233438485805, 5.678233438485805, 4.416403785488958], 
              [21.259050976849895, 3.984063745019917, 4.37956204379562, 4.37956204379562, 2.9197080291970803], 
              [35.15494106848876, 26.086956521739136, 36.36363636363636, 36.36363636363636, 22.727272727272723], 
              [40.62996255772957, 6.211180124223603, 11.956521739130434, 10.869565217391305, 7.608695652173914]
          ], 
          [1.0, 0.8961276818419676, 0.9469724940003692, 0.9504554829838432, 0.9718706392146302, 0.974186156231044, 0.9816530820962593, 0.9820545319648819, 0.9832283601063215, 0.9976122599597702, 0.9976171564733916, 0.997936855267271, 0.9982340004887043, 0.997788870972414, 0.9957361013302978], 
          [0.0003603218170691966, 0.006553090857985063, 0.009900835439958929, 0.008596159745154226, 0.013709546767606629, 0.014609147799420111, 0.020716096990846446, 0.01846826042899463, 0.017892623256256103, 0.016787531460245256, 0.015502240929898709, 0.017609245634691878, 0.020195789917802593, 0.023179642244685786, 0.021880474311675096], 
          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
          [
              [0, 72, 0, 0, 0, 157], 
              [24, 157, 49, 9, 0, 233], 
              [97, 233, 251, 26, 1, 292], 
              [89, 292, 339, 10, 0, 367], 
              [141, 367, 394, 52, 0, 400], 
              [81, 400, 275, 25, 0, 460], 
              [124, 460, 364, 73, 1, 472], 
              [56, 470], 
              [0, 580, 0, 27, 1, 638], 
              [0, 638, 0, 23, 0, 700], 
              [95, 700, 120, 72, 0, 713], 
              [73, 713, 107, 70, 0, 728], 
              [55, 728, 76, 89, 10, 724], 
              [0, 724, 0, 40, 1, 769]
            ]
        ]

In [3]:
# TCLP random
result = [[239.0, 442.0, 645.0, 848.0, 1051.0, 1254.0, 1457.0, 1660.0, 1863.0, 2066.0, 2269.0, 2472.0, 2675.0, 2878.0, 3081.0], 
          [486.0, 5499.0, 5902.0, 50786.0, 51595.0, 97004.0, 97517.0, 145530.0, 146063.0, 146407.0, 199750.0, 205123.0, 215978.0, 256933.0, 256214.0], 
          [
              [68.57934552053065, 17.258382642998026, 24.181360201511335, 22.83795130142737, 21.326616288832913], 
              [63.917190814237195, 20.27833001988072, 27.352941176470587, 27.058823529411768, 18.235294117647058], 
              [64.12071946150733, 18.80650994575045, 27.94520547945205, 26.3013698630137, 18.08219178082192], 
              [65.26158335478966, 19.38382541720154, 28.66108786610878, 26.987447698744777, 22.384937238493723], 
              [66.89287772342173, 22.740963855421693, 32.342449464922716, 30.202140309155762, 24.97027348394768], 
              [61.20388420936477, 56.830601092896174, 55.55555555555556, 55.00000000000001, 47.22222222222223], 
              [47.22416350952048, 52.542372881355924, 64.42953020134229, 49.66442953020134, 48.99328859060402], 
              [35.126469758830815, 29.378531073446325, 19.33085501858736, 9.66542750929368, 7.434944237918216], 
              [35.868245852797294, 29.378531073446325, 19.771863117870723, 9.885931558935361, 9.1254752851711], 
              [47.894214146467064, 43.31983805668016, 28.30188679245283, 17.924528301886795, 9.90566037735849], 
              [84.90025870207575, 51.05740181268883, 64.56692913385827, 62.99212598425197, 55.905511811023615], 
              [81.48073221269969, 66.798418972332, 72.55813953488372, 71.16279069767441, 65.11627906976743], 
              [79.72315199666507, 63.348416289592755, 72.8643216080402, 69.84924623115577, 56.28140703517589], 
              [75.72982185112983, 23.73595505617978, 35.9955005624297, 32.170978627671545, 29.471316085489313], 
              [87.52835301185615, 73.11320754716981, 81.74807197943444, 81.23393316195371, 73.0077120822622]
            ], 
            [1.0, 0.999818148754319, 0.9998305659098611, 0.9991926908990667, 0.9992053493555577, 0.9874541256030679, 0.9875508885630198, 0.9912732769875627, 0.9913461999274286, 0.9913665330209621, 0.9936020025031289, 0.9950858753040859, 0.9953467482799174, 0.9967540175843508, 0.9967449085530065], 
            [0.0010565489975818607, 0.009469541542940897, 0.006909206242275064, 0.02527343812866671, 0.0211201957786158, 0.033798885070698295, 0.029747696506846888, 0.05780164884311863, 0.05198416505715656, 0.04721095385897279, 0.057190948409059444, 0.055412446858001306, 0.05792843198486943, 0.06695398927211213, 0.062283165333427364], 
            [0.17436974789915966, 0.16859122401847576, 0.17063492063492064, 0.17082785808147175, 0.16720257234726688, 0.16962524654832348, 0.1695059625212947, 0.1711864406779661, 0.1720877458396369, 0.17294520547945205, 0.175177304964539, 0.1727989487516426, 0.17264150943396225, 0.1740625, 0.17514619883040936], 
            [
                [0, 36, 0, 1, 0, 238], 
                [44, 238, 75, 8, 0, 433], 
                [0, 433, 0, 6, 0, 630], 
                [140, 630, 346, 72, 0, 761], 
                [0, 761, 0, 31, 0, 933], 
                [227, 933, 580, 122, 5, 1014], 
                [0, 1014, 0, 43, 0, 1174], 
                [342, 1174, 621, 197, 0, 1180], 
                [0, 1180, 0, 61, 1, 1322], 
                [0, 1322, 0, 65, 0, 1460], 
                [220, 1460, 47, 253, 1, 1410], 
                [116, 1410, 188, 91, 1, 1522], 
                [201, 1522, 373, 135, 0, 1590], 
                [310, 1590, 393, 193, 2, 1600], 
                [41, 1600, 97, 93, 0, 1710]
            ]
        ]

In [7]:
# TCLP conf
result = [[239.0, 442.0, 645.0, 848.0, 1051.0, 1254.0, 1457.0, 1660.0, 1863.0, 2066.0, 2269.0, 2472.0, 2675.0, 2878.0, 3081.0], [458.0, 2653.0, 29363.0, 33199.0, 46774.0, 51458.0, 57579.0, 60196.0, 94469.0, 91161.0, 89822.0, 91455.0, 94267.0, 94393.0, 95564.0], [[52.14318117727836, 4.9000392003136, 8.284457478005866, 6.744868035190617, 5.718475073313782], [34.282316303135076, 9.589041095890416, 8.327137546468402, 5.5018587360594795, 4.758364312267658], [42.47373131766408, 17.303822937625757, 25.519287833827892, 25.519287833827892, 24.33234421364985], [46.75396329127892, 34.75177304964539, 32.6797385620915, 32.6797385620915, 31.808278867102395], [15.2934613356874, 28.8135593220339, 9.929078014184396, 1.4184397163120568, 0.0], [59.28446193646473, 47.840531561461795, 53.97489539748954, 47.280334728033466, 35.98326359832636], [73.15444881744952, 72.5, 68.96551724137932, 68.96551724137932, 61.00795755968169], [73.6430401785167, 52.83582089552239, 58.59375, 53.90625, 50.781250000000014], [77.90794619977686, 72.10526315789474, 82.83378746594006, 82.28882833787466, 70.29972752043597], [68.40401662559312, 54.3046357615894, 64.30062630480168, 55.11482254697286, 43.84133611691023], [76.90746803006338, 69.377990430622, 79.27461139896373, 77.720207253886, 69.43005181347152], [80.68071749978543, 66.52360515021459, 76.09756097560975, 74.6341463414634, 68.78048780487805], [73.98450239697895, 66.82242990654206, 76.21483375959079, 73.65728900255753, 62.40409207161126], [78.37569426564167, 63.48547717842323, 73.20574162679426, 72.2488038277512, 67.46411483253588], [81.1889260798666, 75.40983606557377, 84.44444444444443, 83.8888888888889, 73.88888888888889]], [1.0, 1.0, 0.45410891257705277, 0.5318232476881833, 0.6656262025911831, 0.6894166116055812, 0.7156775907883083, 0.7283540434580371, 0.8262922228455896, 0.819988811004706, 0.8254770546191357, 0.8376687988628287, 0.8422990017715638, 0.8420009958365556, 0.841980243606379], [0.002169288302383723, 0.005910147771624277, 0.012009277181515393, 0.01658130083001335, 0.02465474590160747, 0.024865250538670492, 0.032472780600761794, 0.035348323906424575, 0.05720345425307972, 0.051474562842464947, 0.04941023434744834, 0.05132686364364238, 0.05126281505936036, 0.049583561807007376, 0.04838973287776892], [0.16292134831460675, 0.140625, 0.14285714285714285, 0.13279132791327913, 0.15661252900232017, 0.16132478632478633, 0.158, 0.15612648221343872, 0.1586433260393873, 0.16804123711340208, 0.16765873015873015, 0.1676190476190476, 0.16666666666666666, 0.16845878136200718, 0.1658206429780034], [[0, 36, 0, 150, 0, 89], [10, 89, 19, 100, 0, 192], [23, 192, 93, 97, 9, 301], [33, 301, 62, 135, 7, 369], [40, 369, 210, 141, 9, 431], [31, 431, 95, 166, 1, 468], [59, 468, 137, 171, 7, 500], [34, 500, 70, 197, 0, 506], [139, 506, 149, 252, 1, 457], [53, 457, 95, 175, 1, 485], [30, 485, 62, 184, 0, 504], [63, 504, 258, 183, 7, 525], [84, 525, 194, 188, 0, 540], [50, 540, 167, 185, 1, 558], [39, 558, 199, 170, 6, 591]]]

In [8]:
for row in result:
    print(len(row))

15
15
15
15
15
15
15

In [9]:
array_result = result[0:2] + result[3:6]
test_acc_result = result[2]
plateau_log_result = result[6]

In [10]:
for i in array_result:
    print(len(i), end=" - ")
    for j in i:
        print(j, end=" ")
    print()

15 - 239.0 442.0 645.0 848.0 1051.0 1254.0 1457.0 1660.0 1863.0 2066.0 2269.0 2472.0 2675.0 2878.0 3081.0
15 - 458.0 2653.0 29363.0 33199.0 46774.0 51458.0 57579.0 60196.0 94469.0 91161.0 89822.0 91455.0 94267.0 94393.0 95564.0
15 - 1.0 1.0 0.45410891257705277 0.5318232476881833 0.6656262025911831 0.6894166116055812 0.7156775907883083 0.7283540434580371 0.8262922228455896 0.819988811004706 0.8254770546191357 0.8376687988628287 0.8422990017715638 0.8420009958365556 0.841980243606379
15 - 0.002169288302383723 0.005910147771624277 0.012009277181515393 0.01658130083001335 0.02465474590160747 0.024865250538670492 0.032472780600761794 0.035348323906424575 0.05720345425307972 0.051474562842464947 0.04941023434744834 0.05132686364364238 0.05126281505936036 0.049583561807007376 0.04838973287776892
15 - 0.16292134831460675 0.140625 0.14285714285714285 0.13279132791327913 0.15661252900232017 0.16132478632478633 0.158 0.15612648221343872 0.1586433260393873 0.16804123711340208 0.16765873015873015 0.1676190476190476 0.16666666666666666 0.16845878136200718 0.1658206429780034

In [12]:
for i in test_acc_result:
    print(len(i), " - ", i)

5  -  [52.14318117727836, 4.9000392003136, 8.284457478005866, 6.744868035190617, 5.718475073313782]
5  -  [34.282316303135076, 9.589041095890416, 8.327137546468402, 5.5018587360594795, 4.758364312267658]
5  -  [42.47373131766408, 17.303822937625757, 25.519287833827892, 25.519287833827892, 24.33234421364985]
5  -  [46.75396329127892, 34.75177304964539, 32.6797385620915, 32.6797385620915, 31.808278867102395]
5  -  [15.2934613356874, 28.8135593220339, 9.929078014184396, 1.4184397163120568, 0.0]
5  -  [59.28446193646473, 47.840531561461795, 53.97489539748954, 47.280334728033466, 35.98326359832636]
5  -  [73.15444881744952, 72.5, 68.96551724137932, 68.96551724137932, 61.00795755968169]
5  -  [73.6430401785167, 52.83582089552239, 58.59375, 53.90625, 50.781250000000014]
5  -  [77.90794619977686, 72.10526315789474, 82.83378746594006, 82.28882833787466, 70.29972752043597]
5  -  [68.40401662559312, 54.3046357615894, 64.30062630480168, 55.11482254697286, 43.84133611691023]
5  -  [76.90746803006338, 69.377990430622, 79.27461139896373, 77.720207253886, 69.43005181347152]
5  -  [80.68071749978543, 66.52360515021459, 76.09756097560975, 74.6341463414634, 68.78048780487805]
5  -  [73.98450239697895, 66.82242990654206, 76.21483375959079, 73.65728900255753, 62.40409207161126]
5  -  [78.37569426564167, 63.48547717842323, 73.20574162679426, 72.2488038277512, 67.46411483253588]
5  -  [81.1889260798666, 75.40983606557377, 84.44444444444443, 83.8888888888889, 73.88888888888889]

In [28]:
import numpy as np

np.save("array.npy", array_result)

In [29]:
for i in test_acc_result:
    print(len(i), " - ", i)

5  -  [27.277495301504974, 1.7137960582690681, 1.0084033613445378, 0.6722689075630254, 0.3361344537815127]
5  -  [44.8943020731654, 1.8939393939393923, 1.2974976830398517, 1.2974976830398517, 0.9267840593141798]
5  -  [33.19249989073268, 1.2908777969018903, 1.0126582278481016, 0.6751054852320675, 0.33755274261603374]
5  -  [36.89447690088725, 1.620370370370372, 1.3528748590755355, 1.1273957158962795, 0.6764374295377678]
5  -  [42.647765847404536, 1.7402945113788482, 2.3376623376623376, 2.3376623376623376, 1.2987012987012987]
5  -  [38.41256428561022, 1.498637602179842, 1.8494055482166447, 1.5852047556142663, 1.0568031704095113]
5  -  [27.83257331837585, 1.3803680981595123, 1.1851851851851851, 0.8888888888888888, 0.5925925925925926]
5  -  [30.383601159690556, 0.770925110132159, 1.0741138560687435, 0.8592910848549948, 0.644468313641246]
5  -  [20.816154081498855, 1.3333333333333308, 1.6913319238900635, 1.6913319238900635, 0.0]
5  -  [35.322484301927474, 9.734513274336287, 13.23529411764706, 11.76470588235294, 7.352941176470589]
5  -  [36.53462317341453, 4.8128342245989275, 8.57142857142857, 7.619047619047619, 6.666666666666667]
5  -  [35.95769169131252, 3.74149659863946, 5.678233438485805, 5.678233438485805, 4.416403785488958]
5  -  [21.259050976849895, 3.984063745019917, 4.37956204379562, 4.37956204379562, 2.9197080291970803]
5  -  [35.15494106848876, 26.086956521739136, 36.36363636363636, 36.36363636363636, 22.727272727272723]
5  -  [40.62996255772957, 6.211180124223603, 11.956521739130434, 10.869565217391305, 7.608695652173914]

In [30]:
np.save("test_acc.npy", test_acc_result)

In [31]:
for i in plateau_log_result:
    print(len(i), " - ", i)

6  -  [0, 72, 0, 0, 0, 157]
6  -  [24, 157, 49, 9, 0, 233]
6  -  [97, 233, 251, 26, 1, 292]
6  -  [89, 292, 339, 10, 0, 367]
6  -  [141, 367, 394, 52, 0, 400]
6  -  [81, 400, 275, 25, 0, 460]
6  -  [124, 460, 364, 73, 1, 472]
2  -  [56, 470]
6  -  [0, 580, 0, 27, 1, 638]
6  -  [0, 638, 0, 23, 0, 700]
6  -  [95, 700, 120, 72, 0, 713]
6  -  [73, 713, 107, 70, 0, 728]
6  -  [55, 728, 76, 89, 10, 724]
6  -  [0, 724, 0, 40, 1, 769]

In [34]:
array_part = np.load("HAPT_MSTCN_noplatprob_random_0.8_10_2.0_0_arrays.npy", allow_pickle=True)

print(array_part)
print(array_part.shape)  # Outputs the shape of the array

[[2.39000000e+02]
 [4.78000000e+02]
 [1.00000000e+00]
 [9.60650990e-04]
 [1.82008368e-01]]
(5, 1)

In [35]:
array_part = np.load("HAPT_MSTCN_noplatprob_random_0.8_10_2.0_0_test_acc.npy", allow_pickle=True)

print(array_part)
print(array_part.shape)  # Outputs the shape of the array

[[74.44305489 26.62440571 34.15841584 34.15841584 29.20792079]]
(1, 5)