# Learn About Apartment Data

https://mlbook.explained.ai/intro.html

In [40]:
import pandas as pd
df = pd.read_csv("../data/rent-ideal.csv")

In [41]:
df.head()

   bedrooms  bathrooms  latitude  longitude  price
0         1        1.0   40.7108   -73.9539   2400
1         2        1.0   40.7513   -73.9722   3800
2         2        1.0   40.7575   -73.9625   3495
3         3        1.5   40.7145   -73.9425   3000
4         0        1.0   40.7439   -73.9743   2795

In [42]:
df.head().T

                   0          1          2          3          4
bedrooms      1.0000     2.0000     2.0000     3.0000     0.0000
bathrooms     1.0000     1.0000     1.0000     1.5000     1.0000
latitude     40.7108    40.7513    40.7575    40.7145    40.7439
longitude   -73.9539   -73.9722   -73.9625   -73.9425   -73.9743
price      2400.0000  3800.0000  3495.0000  3000.0000  2795.0000

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48300 entries, 0 to 48299
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   bedrooms   48300 non-null  int64
 1   bathrooms  48300 non-null  float64
 2   latitude   48300 non-null  float64
 3   longitude  48300 non-null  float64
 4   price      48300 non-null  int64
dtypes: float64(3), int64(2)
memory usage: 1.8 MB

In [44]:
df.columns

Index(['bedrooms', 'bathrooms', 'latitude', 'longitude', 'price'], dtype='object')

In [45]:
df.describe()

           bedrooms     bathrooms      latitude     longitude         price
count  48300.000000  48300.000000  48300.000000  48300.000000  48300.000000
mean       1.508799      1.178313     40.750782    -73.972365   3438.297950
std        1.092232      0.426120      0.039560      0.029563   1401.422247
min        0.000000      0.000000     40.571200    -74.094000   1025.000000
25%        1.000000      1.000000     40.728100    -73.991700   2495.000000
50%        1.000000      1.000000     40.751600    -73.977900   3100.000000
75%        2.000000      1.000000     40.774000    -73.954700   4000.000000
max        8.000000     10.000000     40.915400    -73.700100   9999.000000

In [46]:
df.mean()

bedrooms        1.508799
bathrooms       1.178313
latitude       40.750782
longitude     -73.972365
price        3438.297950
dtype: float64

In [47]:
df.bedrooms.value_counts()

bedrooms
1    15718
2    14451
0     9436
3     6777
4     1710
5      169
6       36
8        2
7        1
Name: count, dtype: int64

In [48]:
df.sort_values('price', ascending=False).head()

       bedrooms  bathrooms  latitude  longitude  price
20589         3        3.0   40.7934   -73.9743   9999
3784          6        3.0   40.7287   -73.9856   9999
11598         6        3.0   40.7287   -73.9856   9999
43789         3        3.0   40.7602   -73.9597   9995
43085         2        2.5   40.7285   -73.9902   9995

In [50]:
df.price.head()

0    2400
1    3800
2    3495
3    3000
4    2795
Name: price, dtype: int64

In [51]:
prices = df.price
prices.min(), prices.mean(), prices.max()

(1025, 3438.297950310559, 9999)

In [53]:
df[['bedrooms', 'price']].head()

   bedrooms  price
0         1   2400
1         2   3800
2         2   3495
3         3   3000
4         0   2795